### ISSUE TITLE
Suggestion: BiStracker

### ISSUE THREAD

**Issue by JmyhDK** [Zentarg/BiSTracker#11]
First of all I like the new UI. Its a nice improvement to the old one.

I understand this is the first version of the new layout, but would you please consider either to have the addon remember the placement of Minimap Button, or make a choice to disable it. 

If I move the button to the desired place, it resets on /reload or next login at WoW.

Thank you,
JmyhDK

**Comment by Zentarg** [comment]
Working on this next
