### ISSUE TITLE
Problem and suggestion

### ISSUE THREAD

**Issue by LiozProb** [Zentarg/BiSTracker#12]
Hi, I updated to the latest version of addon (with twitch app) and the interface changed from good to very good, but it only shows me the BIS of the last phases (P5-P6), not like before it showed me the prebis p1 p2 p3 etc. If I start a new character this addon will be useless.

I recommend keeping the information for prebis, p1, p2, etc. to keep an advance on any character

**Comment by Zentarg** [comment]
I'm currently looking for a way to reintroduce those sets, without cluttering up the sets list. A phase dropdown is sadly not a feasable solution as that would require a complete rewrite of the data handling. 

How would you feel about making it possible to import them as a custom set?

**Comment by LiozProb** [comment]
Ty for the update!
