### ISSUE TITLE
Obtain method is reseted on editing an entry

### ISSUE THREAD

**Issue by miracle152005** [Zentarg/BiSTracker#19]
I created a custom set and defined the Obtain method as "By Quest".
If I now edit it again the method is reseted to "By Killing".
If I then switch it again to "By Quest" all values are cleared.

Could you please take a look?

Thanks.

**Comment by miracle152005** [comment]
Seems to be reproducable only some of the time.

**Comment by Zentarg** [comment]
I've made some changes as to how the entire edit custom sets work, so this issue should be irrelevant come next update.

Please reopen the issue if the bug reoccurs.

Curseforge is currently down, so I can't upload the recent update. I will update it as soon as Curseforge is back up.
