### ISSUE TITLE
Suggestion: Add a by Vendor Option

### ISSUE THREAD

**Issue by miracle152005** [Zentarg/BiSTracker#20]
Some of my pre-Raid BiS like the Blood Knight Warcloack (https://tbc.wowhead.com/item=29382/blood-knight-war-cloak) have to be bought by using Badge of Justice.
Would it be possible to add a By Vendor Option?

Thanks.

**Comment by Zentarg** [comment]
Already done. Waiting for Curseforge to be back up, so that I can update the addon.
