### ISSUE TITLE
By Recipe Item does not list any information on mouse over

### ISSUE THREAD

**Issue by miracle152005** [Zentarg/BiSTracker#22]
I added "https://tbc.wowhead.com/spell=32493/fel-leather-boots" as a BiS item in a custom set by recipe.
The Icon is displayed but on mouse over no Information is provided.

Could you take a look.

Thanks.

**Comment by Zentarg** [comment]
Every item should be added with the itemID.

So you would put the itemID of https://tbc.wowhead.com/item=25686/fel-leather-boots, and not the spellID that you linked :)

If you did indeed do as I just said, then please send a screenshot of your mouseover, and any lua errors that might have occured. (You can check these with the addon bugsack)

**Comment by miracle152005** [comment]
Sorry, don't know what happend there. I added a the correct item Id (at least if I search for it).
But somehow it was still wrong.
I added the item again and now it works.
