### ISSUE TITLE
No Wrath

### ISSUE THREAD

**Issue by marulol** [Zentarg/BiSTracker#30]
Only shows tbc bis no wrath

**Comment by Zentarg** [comment]
For now the addon has only been updated to actuall function using the wrath client.

I'm working on updating the tool that pulls item information from wowhead, which powers both the auto-fill for custom sets and the item-information for bis sets.

**Comment by Zentarg** [comment]
A new release has been made with wotlk BiS sets including updated autofill data: https://github.com/Zentarg/BiSTracker/releases/tag/6.01
