### ISSUE TITLE
Red Bar

### ISSUE THREAD

**Issue by DeadheadDev** [Zentarg/BiSTracker#32]
Hey love the addon! 

I seem to be getting this red bar however to the right of center when install. Any ideas what might be causing it? 

![image](https://github.com/Zentarg/BiSTracker/assets/88709822/59242c9b-1076-4a2b-b35d-b4d92b292e3f)

**Comment by Zentarg** [comment]
I can't seem to replicate this issue.

Do you have any other addons enabled?
