### ISSUE TITLE
Updates for current phases

### ISSUE THREAD

**Issue by evanhfox** [Zentarg/BiSTracker#4]
Any updates planned to match the current phase (3, BWL)?

**Comment by Warkdev** [comment]
Hi,

I don't think that Zentarg is keeping the add-on up-to-date. Feel free to submit a PR or use another one.

Wark

**Comment by Zentarg** [comment]
Correct, I no longer maintain the addon. Any updates will come from volunteers contributing via pull requests.

**Comment by evanhfox** [comment]
Thank you, gents! I'll consider submitting a PR.

Hope everyone is healthy.

**Comment by Warkdev** [comment]
Hello evanhfox,

I think Zentarg won't see any offense to what I'll say but thanks to him and his work, I've written a complete add-on doing this. You can search for best in slot classic on twitch.

Feel free to participate as it's maintained as well. 

https://github.com/Warkdev/BestInSlotClassic

Wark

**Comment by astothialo** [comment]
Thank you Zentarg, the people who maintained this and to Warkdev.
Great work everyone much appreciated!

**Comment by Zentarg** [comment]
Thanks to Braatak, the addon has now been updated all the way till phase 6.

**Comment by astothialo** [comment]
excelent!
Although idols wont be ingame till phase 6 or something?
