### ISSUE TITLE
wow classic problem, issues with the new version of ICON

### ISSUE THREAD

**Issue by yadgen** [Zentarg/BiSTracker#7]
Update to version 2.5.1, there is a problem, please see the picture.
![1](https://user-images.githubusercontent.com/1206012/90750826-f43aec80-e307-11ea-99d2-5148c8396235.png)

**Comment by Reydas** [comment]
Yesterday I installed the BiSTracker_2.5.zip update and everything was fine, I was even pleasantly surprised that the add-on icon became to the left of the Outfitter - Classic add-on icon, which became convenient. But the update BiSTracker_2.5.1.zip has the same problem as the author of the topic.
![image](https://user-images.githubusercontent.com/65668304/90759787-9b5c5b80-e2e9-11ea-8e7f-0454de5250ad.png)

**Comment by Zentarg** [comment]
This should already have been fixed on the curseforge version.
